language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "8"
env:
  global:
    - COVERALLS_REPO_TOKEN=sqDxXMd01aMtd3rb6tzOL8BsrsUOV4I66
cache:
  directories:
    - node_modules
after_script:
  - npm run coveralls
sudo: false
